"""
export_service.py — Conversation PDF Export Service
Generates print-friendly, beautifully typeset PDF dossiers for study notes,
structured Q&A turns, inline citations, per-response source excerpts,
and a consolidated references index at the end.
"""

import io
import re
from datetime import datetime
from typing import List, Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas


def slugify(value: str) -> str:
    """Converts a title into a URL/filename-safe lowercase slug."""
    if not value:
        return "conversation-export"
    s = re.sub(r'[^\w\s-]', '', value).strip().lower()
    s = re.sub(r'[-\s]+', '-', s)
    return s[:60] or "conversation-export"


def _sanitize_for_reportlab(text: str) -> str:
    """
    Safely converts Markdown text into ReportLab-compatible XML markup:
    - Escapes raw XML characters (&, <, >)
    - Converts **bold** to <b>bold</b>
    - Converts *italic* to <i>italic</i>
    - Converts `code` to Courier inline code
    - Highlights citation markers like [1], [2] in vibrant sky blue
    """
    if not text:
        return ""

    # 1. Escape XML characters
    s = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

    # 2. Bold: **text** or __text__
    s = re.sub(r'\*\*(.+?)\*\*', r'<b>\1</b>', s)
    s = re.sub(r'__(.+?)__', r'<b>\1</b>', s)

    # 3. Italic: *text* or _text_
    s = re.sub(r'(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)', r'<i>\1</i>', s)
    s = re.sub(r'(?<!_)_(?!_)(.+?)(?<!_)_(?!_)', r'<i>\1</i>', s)

    # 4. Inline code: `code`
    s = re.sub(r'`(.+?)`', r'<font face="Courier" color="#0F172A">\1</font>', s)

    # 5. Citation tags [1], [2] -> styled badge
    s = re.sub(r'\[(\d+)\]', r'<b><font color="#0284C7">[\1]</font></b>', s)

    return s


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas that dynamically calculates total page count
    and prints a running header and footer on every page.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []
        self.doc_title = "Conversation Export"

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Running Header on pages 2+
        if self._pageNumber > 1:
            title_display = self.doc_title[:65] + ("..." if len(self.doc_title) > 65 else "")
            self.drawString(54, 755, title_display)
            self.drawRightString(612 - 54, 755, "Knowledge AI • Study Notes")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 748, 612 - 54, 748)

        # Running Footer on all pages
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 45, 612 - 54, 45)

        date_str = datetime.utcnow().strftime("%B %d, %Y")
        self.drawString(54, 32, f"Generated by Knowledge AI  •  {date_str}")
        self.drawRightString(612 - 54, 32, f"Page {self._pageNumber} of {page_count}")

        self.restoreState()


def generate_conversation_pdf(
    conversation: Any,
    messages: List[Any],
    citations_map: Dict[str, List[Any]],
) -> bytes:
    """
    Generates a print-friendly, downloadable PDF for a conversation.

    Parameters
    ----------
    conversation : Conversation model instance
    messages : List of Message model instances ordered by created_at asc
    citations_map : Dict mapping message_id -> List[Citation]
    """
    buffer = io.BytesIO()

    # Letter size: 612 x 792 pt, 0.75-inch (54 pt) margins
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    # Styles
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#0F172A'),
        spaceAfter=6,
    )

    meta_style = ParagraphStyle(
        'DocMeta',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor('#64748B'),
    )

    q_badge_style = ParagraphStyle(
        'QBadge',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor('#0369A1'),
    )

    q_text_style = ParagraphStyle(
        'QText',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=11,
        leading=15,
        textColor=colors.HexColor('#0F172A'),
        spaceAfter=4,
    )

    a_label_style = ParagraphStyle(
        'ALabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=colors.HexColor('#0284C7'),
        spaceAfter=4,
    )

    body_style = ParagraphStyle(
        'ABody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=6,
    )

    source_head_style = ParagraphStyle(
        'SourceHead',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#475569'),
    )

    source_title_style = ParagraphStyle(
        'SourceTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor('#0369A1'),
    )

    source_excerpt_style = ParagraphStyle(
        'SourceExcerpt',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=8,
        leading=11.5,
        textColor=colors.HexColor('#334155'),
    )

    ref_head_style = ParagraphStyle(
        'RefHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#0F172A'),
        spaceAfter=8,
        keepWithNext=True,
    )

    ref_cell_style = ParagraphStyle(
        'RefCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor('#1E293B'),
    )

    ref_cell_bold = ParagraphStyle(
        'RefCellBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor('#0F172A'),
    )

    story = []

    # ── 1. Document Header Banner ────────────────────────────────
    conv_title = conversation.title or "Conversation Notes"
    created_date = (
        conversation.created_at.strftime("%B %d, %Y at %I:%M %p")
        if getattr(conversation, "created_at", None)
        else datetime.utcnow().strftime("%B %d, %Y")
    )
    export_date = datetime.utcnow().strftime("%B %d, %Y at %I:%M %p UTC")
    model_name = getattr(conversation, "model", "Gemini 2.5 Flash")

    story.append(Paragraph("KNOWLEDGE AI  •  STUDY NOTES &amp; RESEARCH DOSSIER", ParagraphStyle(
        'SubHeadTag',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#0284C7'),
        spaceAfter=4,
    )))
    story.append(Paragraph(conv_title, title_style))

    meta_text = (
        f"<b>Session Created:</b> {created_date} &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"<b>Exported:</b> {export_date} &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"<b>Model:</b> {model_name}"
    )
    story.append(Paragraph(meta_text, meta_style))
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=14))

    # ── 2. Build Structured Q&A Turns ───────────────────────────
    turn_pairs = []
    current_user_msg = None

    for m in messages:
        if m.role == "user":
            current_user_msg = m
        elif m.role == "assistant":
            turn_pairs.append({
                "question": current_user_msg.content if current_user_msg else "General Prompt",
                "answer": m.content,
                "model": getattr(m, "model", model_name),
                "citations": citations_map.get(m.id, []),
                "timestamp": m.created_at.strftime("%I:%M %p") if getattr(m, "created_at", None) else "",
            })
            current_user_msg = None

    if current_user_msg:
        turn_pairs.append({
            "question": current_user_msg.content,
            "answer": "<i>(No response generated)</i>",
            "model": model_name,
            "citations": [],
            "timestamp": "",
        })

    consolidated_refs: Dict[str, Dict[str, Any]] = {}

    for turn_idx, turn in enumerate(turn_pairs, start=1):
        turn_elements = []

        # Question Header Box (Light Blue Tint)
        q_text = _sanitize_for_reportlab(turn["question"])
        q_cell_content = [
            Paragraph(f"QUESTION {turn_idx}", q_badge_style),
            Spacer(1, 2),
            Paragraph(f"Q: {q_text}", q_text_style),
        ]
        q_table = Table([[q_cell_content]], colWidths=[504])
        q_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F0F9FF")),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#BAE6FD")),
            ('PADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ]))
        turn_elements.append(q_table)
        turn_elements.append(Spacer(1, 8))

        # Answer Section
        a_sanitized = _sanitize_for_reportlab(turn["answer"])
        turn_elements.append(Paragraph("A: ANSWER", a_label_style))

        for paragraph in a_sanitized.split("\n\n"):
            p_clean = paragraph.strip()
            if not p_clean:
                continue
            if p_clean.startswith("- ") or p_clean.startswith("* "):
                bullet_lines = p_clean.split("\n")
                for bl in bullet_lines:
                    bl_clean = re.sub(r'^[-*]\s+', '', bl.strip())
                    if bl_clean:
                        turn_elements.append(Paragraph(f"&bull;&nbsp;&nbsp;{bl_clean}", ParagraphStyle(
                            'BulletText',
                            parent=body_style,
                            leftIndent=14,
                            spaceAfter=3,
                        )))
            else:
                p_inline = p_clean.replace("\n", " ")
                turn_elements.append(Paragraph(p_inline, body_style))

        # Sources Section for this Turn (if any)
        citations = turn.get("citations", [])
        if citations:
            turn_elements.append(Spacer(1, 4))
            turn_elements.append(Paragraph(f"SOURCES CITED ({len(citations)})", source_head_style))
            turn_elements.append(Spacer(1, 4))

            for c_idx, cit in enumerate(citations, start=1):
                doc_title = getattr(cit, "document_title", "Referenced Document")
                page_num = getattr(cit, "page", None)
                page_str = f"Page {page_num}" if page_num else "Whole Document"
                excerpt = getattr(cit, "excerpt", "").strip()

                ref_key = getattr(cit, "document_id", None) or doc_title
                if ref_key not in consolidated_refs:
                    consolidated_refs[ref_key] = {
                        "title": doc_title,
                        "pages": set(),
                        "count": 0,
                    }
                if page_num:
                    consolidated_refs[ref_key]["pages"].add(page_num)
                consolidated_refs[ref_key]["count"] += 1

                sanitized_excerpt = _sanitize_for_reportlab(excerpt)
                if len(sanitized_excerpt) > 300:
                    sanitized_excerpt = sanitized_excerpt[:300] + "..."

                source_cell = [
                    Paragraph(f"<b>[{c_idx}] {doc_title}</b> &nbsp;&bull;&nbsp; <i>{page_str}</i>", source_title_style),
                    Spacer(1, 2),
                    Paragraph(f'"{sanitized_excerpt}"', source_excerpt_style),
                ]

                source_table = Table([[source_cell]], colWidths=[504])
                source_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                    ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
                    ('LEFTPADDING', (0, 0), (-1, -1), 8),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                    ('TOPPADDING', (0, 0), (-1, -1), 6),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
                ]))
                turn_elements.append(source_table)
                turn_elements.append(Spacer(1, 4))

        # Divider between turns
        turn_elements.append(Spacer(1, 10))
        turn_elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0"), spaceAfter=12))

        story.extend(turn_elements)

    # ── 3. Consolidated References Summary ──────────────────────
    if consolidated_refs:
        ref_story = []
        ref_story.append(Spacer(1, 10))
        ref_story.append(Paragraph("Consolidated References &amp; Cited Sources", ref_head_style))
        ref_story.append(Paragraph(
            "The following documents were referenced to answer queries throughout this study session:",
            meta_style
        ))
        ref_story.append(Spacer(1, 8))

        table_data = [[
            Paragraph("Document Title", ref_cell_bold),
            Paragraph("Pages Cited", ref_cell_bold),
            Paragraph("Total Citations", ref_cell_bold),
        ]]

        for r in consolidated_refs.values():
            sorted_pages = sorted(list(r["pages"]))
            pages_str = ", ".join(f"p. {p}" for p in sorted_pages) if sorted_pages else "Full Doc"
            table_data.append([
                Paragraph(r["title"], ref_cell_style),
                Paragraph(pages_str, ref_cell_style),
                Paragraph(str(r["count"]), ref_cell_style),
            ])

        ref_table = Table(table_data, colWidths=[274, 150, 80])
        ref_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#0F172A")),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#F8FAFC")]),
        ]))
        ref_story.append(ref_table)
        story.append(KeepTogether(ref_story))

    # Build PDF with NumberedCanvas to draw page numbers
    def make_canvas(*args, **kwargs):
        c = NumberedCanvas(*args, **kwargs)
        c.doc_title = conv_title
        return c

    doc.build(story, canvasmaker=make_canvas)

    return buffer.getvalue()
